# Generated by Django 4.2 on 2023-04-28 19:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 4, 29))),
                ('case_number', models.IntegerField(default=0, verbose_name='Номер кейса')),
                ('player_1_score', models.IntegerField(default=0, verbose_name='Счет 1 игрока')),
                ('player_2_score', models.IntegerField(default=0, verbose_name='Счет 2 игрока')),
                ('table_number', models.IntegerField(default=0, verbose_name='Стол')),
                ('game_type', models.CharField(choices=[('CONFLICT', 'Conflict'), ('DISCUSSION', 'Discussion')], default='CONFLICT', max_length=15, verbose_name='Тип игры')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_info', models.ManyToManyField(to='classes.game')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 4, 29))),
                ('conflict_score', models.IntegerField(default=0, verbose_name='Счет конфликты')),
                ('discuss_score', models.IntegerField(default=0, verbose_name='Счет переговоры')),
                ('begin_time', models.TimeField(default=datetime.time(16, 30))),
                ('finish_time', models.TimeField(default=datetime.time(21, 0))),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='classes.gameregister'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='classes.gameregister'),
        ),
    ]
