# Generated by Django 4.2 on 2023-05-12 18:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_gameregister_attendance_alter_game_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('CONFLICT', 'Conflict'), ('DISCUSSION', 'Discussion')], default='CONFLICT', max_length=15, verbose_name='Тип игры')),
                ('name', models.CharField(max_length=250, verbose_name='Название кейса')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Текст кейса')),
            ],
        ),
        migrations.RemoveField(
            model_name='referee',
            name='game_info',
        ),
        migrations.AddField(
            model_name='referee',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 13)),
        ),
        migrations.AddField(
            model_name='referee',
            name='game_type',
            field=models.CharField(choices=[('CONFLICT', 'Conflict'), ('DISCUSSION', 'Discussion')], default='CONFLICT', max_length=15, verbose_name='Тип игры'),
        ),
        migrations.AddField(
            model_name='referee',
            name='table_number',
            field=models.IntegerField(default=0, verbose_name='Стол'),
        ),
    ]
