# Generated by Django 4.2 on 2023-06-08 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_cases_remove_referee_game_info_referee_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_label',
            field=models.CharField(choices=[('Семья', 'Family'), ('Работа', 'Job'), ('Обучение', 'School'), ('Бизнес', 'Business'), ('', 'Default')], default='', max_length=20, verbose_name='Тип игры'),
        ),
        migrations.AddField(
            model_name='cases',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер кейса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_type',
            field=models.CharField(choices=[('Конфликт', 'Conflict'), ('Переговоры', 'Discussion')], default='Конфликт', max_length=15, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 10)),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Конфликт', 'Conflict'), ('Переговоры', 'Discussion')], default='Конфликт', max_length=15, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='gameregister',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 10)),
        ),
        migrations.AlterField(
            model_name='referee',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 10)),
        ),
        migrations.AlterField(
            model_name='referee',
            name='game_type',
            field=models.CharField(choices=[('Конфликт', 'Conflict'), ('Переговоры', 'Discussion')], default='Конфликт', max_length=15, verbose_name='Тип игры'),
        ),
    ]
