# Generated by Django 4.2 on 2023-07-02 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_cases_case_label_cases_number_alter_cases_case_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_label',
            field=models.CharField(choices=[('Бытовые', 'Family'), ('Корпоративные', 'Job'), ('Бизнес', 'Business'), ('Другое', 'Default')], default='Другое', max_length=20, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 8)),
        ),
        migrations.AlterField(
            model_name='gameregister',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 8)),
        ),
        migrations.AlterField(
            model_name='referee',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 8)),
        ),
    ]
