# Generated by Django 4.2 on 2023-07-02 07:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_cases_case_label_alter_game_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_label',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Бытовые', 'Family'), ('Корпоративные', 'Job'), ('Бизнес', 'Business'), ('Другое', 'Default')], default='Другое', max_length=100, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Название кейса'),
        ),
    ]
