# Generated by Django 4.2 on 2023-07-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_cases_case_label_alter_cases_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название кейса'),
        ),
    ]
