# Generated by Django 4.2 on 2023-07-09 13:57

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_cases_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_label',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Бытовые', 'Family'), ('Корпоративные', 'Job'), ('Бизнес', 'Business'), ('Другое', 'Default')], default='Другое', max_length=100, verbose_name='Категория ситуации'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 15)),
        ),
        migrations.AlterField(
            model_name='gameregister',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 15)),
        ),
        migrations.AlterField(
            model_name='referee',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 15)),
        ),
    ]
