# Generated by Django 4.2 on 2023-07-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_cases_case_label_alter_game_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='label',
            field=models.ManyToManyField(to='classes.gamelabel'),
        ),
    ]
