# Generated by Django 4.2 on 2023-07-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_gamelabel_cases_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='case_label',
        ),
    ]
