# Generated by Django 4.2 on 2023-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_remove_cases_case_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='label',
            field=models.ManyToManyField(to='classes.gamelabel', verbose_name='Категория'),
        ),
    ]
