# Generated by Django 4.1.7 on 2023-04-13 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hse_pass',
            field=models.BooleanField(default=False, verbose_name='Есть пропуск в Вышку'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Заявка принята'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_bot_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='id for telegram bot'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('arbitrator', 'Arbitrator'), ('admin', 'Admin')], default='user', max_length=30, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Ник в Телеграме'),
        ),
    ]
