# Generated by Django 4.1.7 on 2023-03-26 13:46

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from users.models import User
import logging

logger = logging.getLogger(__name__)
def add_group_permissions():
    user_types = ContentType.objects.get_for_model(User)
    user_perms = Permission.objects.filter(content_type=user_types)
    all_user_perms = [i.codename for i in user_perms]
    #standard
    group, created = Group.objects.get_or_create(name='Mentor')
    if created:
        for permission in all_user_perms:
            group.permissions.add(Permission.objects.get(codename=permission, content_type=user_types))
        logger.info('mentor Group created')

    #student
    group, created = Group.objects.get_or_create(name='Student')
    if created:
        logger.info('student Group created')



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
