# Generated by Django 4.1.7 on 2023-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230326_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Участник'), (2, 'Ментор')], null=True, verbose_name='Статус'),
        ),
    ]
