# Generated by Django 4.1.7 on 2023-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hse_pass',
            field=models.BooleanField(default=False, verbose_name='Есть пропуск в Вышку'),
        ),
    ]
