# Generated by Django 4.1.7 on 2023-03-26 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Ник в Телеграме'),
        ),
    ]
