# Generated by Django 4.2 on 2023-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=None, verbose_name='Заявка принята'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_bot_id',
            field=models.URLField(blank=True, default=None, max_length=60, null=True, verbose_name='id for telegram bot'),
        ),
    ]
