# Generated by Django 4.2 on 2023-04-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_accepted_alter_user_tg_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=None, null=True, verbose_name='Заявка принята'),
        ),
    ]
